### ISSUE TITLE
[Feature] Menu met filters

### ISSUE THREAD

**Issue by Sheepolution** [lekkersicko/lekkersicko.github.io#1]
Een (uitklapbaar) menu waar je kan filteren op de elementen waar je op zoekt.

Zoeken op
* Games
* Titel
* Tags

Met filters
* Voor/na datum
* Duurt langer/korter dan tijd
* Waar één/meerdere games worden gespeeld

Van het type
* Stream
* Video
* Podcast

**Comment by Mikko5** [comment]
Filteren van videoType werkt, het design moet alleen nog gemaakt worden

![image](https://github.com/lekkersicko/lekkersicko.github.io/assets/101633673/da51761b-79d3-4fab-8765-713e49627537)

**Comment by Sheepolution** [comment]
Het probleem met dit is dat alles naar beneden wordt geduwd. Ik zie liever de filters aan de zijkant.

**Comment by superruudje** [comment]
Er kan nu gefilterd worden op type, datum, duur en activiteit.
