### ISSUE TITLE
[Bug] Website crash bij klikken op random knop als zoekresultaten minder dan 12 heeft

### ISSUE THREAD

**Issue by braxshinoa** [lekkersicko/lekkersicko.github.io#108]
![image](https://github.com/lekkersicko/lekkersicko.github.io/assets/158345413/7b881e27-275e-45e9-a5bf-4a90ca4bbcb3)

**Comment by braxshinoa** [comment]
![image](https://github.com/lekkersicko/lekkersicko.github.io/assets/158345413/14d332c6-d738-44c0-80b5-3e7a6b77ba07)

**Comment by braxshinoa** [comment]
misschien random gray out als de filter geen random search mogelijk maakt door te weinig resultaten in de search

**Comment by superruudje** [comment]
Kan issue niet reproduceren, waarschijnlijk is het al verholpen. Ik sluit hem voor nu.
