### ISSUE TITLE
[Feature] In een serie overzicht kunnen filteren van nieuw naar oud

### ISSUE THREAD

**Issue by braxshinoa** [lekkersicko/lekkersicko.github.io#116]

**Comment by superruudje** [comment]
Ik zie het sorteren als volgt voor me:
- A - Z / Z - A (titel van de collectie)
- Aanmaakdatum up/down (datum waarop de eerste VOD van de collectie was)
- Update datum up/down (datum waarop de collectie het laatst is geupdated met een nieuwe VOD)
