### ISSUE TITLE
[Feature] Discord embedding

### ISSUE THREAD

**Issue by Sheepolution** [lekkersicko/lekkersicko.github.io#20]
Wanneer ik een specifeke video deel op Discord zou het mooi zijn als de belangrijkste informatie al in de embed beschikbaar is.

Zie https://stackoverflow.com/questions/59335731/how-to-create-own-embed-site-for-discord

**Comment by superruudje** [comment]
@Sheepolution , ik heb hier even mee gespeeld maar kom helaas tot de conclusie dat dit niet werkt voor de single items. De bots die de metadata ophalen doen dit zonder dat er js code wordt uitgevoerd. En omdat de Vue app dynamisch de meta tags aan moet passen met js, kunnen we dus niet de juiste meta gegevens meesturen. 

We kunnen 2 dingen doen:
1. Helemaal geen metatags toevoegen voor platforms als Discord, X, FaceBook enz.
2. Algemene metatags instellen die dus voor elk item hetzelfde zijn. Dat kan er dan als volgt uit zien:
<img width="527" alt="Screenshot 2024-02-27 at 22 00 33" src="https://github.com/lekkersicko/lekkersicko.github.io/assets/158449657/467d626d-da6b-4154-818c-49aa9ec92bf7">

Nadeel hiervan is dat de metadata eigenlijk een link naar de homepage bevat en dus niet naar het specifieke item.

**Comment by Sheepolution** [comment]
Ja laten we in dat geval de algemene embed maken. Misschien leuk als we iets van een logo hebben.
