### ISSUE TITLE
[Feature] Sorteren

### ISSUE THREAD

**Issue by Sheepolution** [lekkersicko/lekkersicko.github.io#23]
Relevant aan #1. Naast een menu met filters zou het ook mooi zijn als de resultaten gesorteerd kunnen worden.

Opties (voor alles ascending/descending):
* Datum
* Titel
* Game (de eerste game in het geval van meerdere)
* Type
* Lengte

**Comment by superruudje** [comment]
Sorteren kan op datum en duur, beide asc/desc.
