### ISSUE TITLE
[Feature] Collecties/Playlists

### ISSUE THREAD

**Issue by Sheepolution** [lekkersicko/lekkersicko.github.io#3]
Er zijn een hoop series waarbij ze een game voor meerdere streams/video's spelen. Denk aan The Lion King, Rust, Cuphead, Resident Evil, en nog veel meer.

Wanneer je op een stream klikt die onderdeel is van een collectie, dan zou het handig zijn als er een knop was die je alle video's van die collectie laat zien. Wellicht moet hier een aparte filter voor komen, en dan het klikken op de knop simpelweg de zoekactie voor je uitvoert.

Dit vereist een aanpassing in de JSONs.

**Comment by braxshinoa** [comment]
hiervoor heb ik al een elke collectie een collectie id gegeven en deze gekoppeld aan de juiste streams, als iemand hiermee aan de slag wilt moeten we dit even uit de excel sheet trekken
