### ISSUE TITLE
"gratis te zien" label 

### ISSUE THREAD

**Issue by braxshinoa** [lekkersicko/lekkersicko.github.io#36]
label of iets dergelijks bij streams die gratis te zien zijn op youtube. Label moet goed duidelijk omhoog springen 
https://www.youtube.com/playlist?list=PLgrEkzz5vpwzjFBqXsviXdPpMKH4Ffi7W
gratis stream playlist

**Comment by Sheepolution** [comment]
Dit vereist een aanpassing in de JSON. Zie [deze issue](https://github.com/lekkersicko/lekker-data/issues/12)

**Comment by braxshinoa** [comment]
data staat erin, kan nu worden aangepast in de frontend
