### ISSUE TITLE
[Feature] Op info pagina van een stream zien of deze geen paywall heeft

### ISSUE THREAD

**Issue by braxshinoa** [lekkersicko/lekkersicko.github.io#80]

**Comment by superruudje** [comment]
@braxshinoa , even voor de check. Alles op Twitch is in principe paywall TENZIJ de property `free = true`? En alle YouTube videos zijn ook zonder paywall toch?

**Comment by braxshinoa** [comment]
Elke twitch stream heeft een paywall
Elke youtube stream op het kanaal van lekker spelen heeft een paywall BEHALVE als deze eraf is gehaald
Alles met de free true tag in de json heb ik met de hand nagekeken en opgezocht in de playlist
Dus in de json kunnen alleen youtube streams free zijn

**Comment by braxshinoa** [comment]
youtube videos dus niet streams hebben sowieso geen paywall

**Comment by superruudje** [comment]
@braxshinoa , enig idee hoe we het zullen tonen? Is dit voldoende?

![Screenshot 2024-09-30 at 14 44 20](https://github.com/user-attachments/assets/9b9a99e4-3222-4d5f-9b54-8cd1b446f673)

**Comment by braxshinoa** [comment]
alleen tonen als de stream gratis is in plaats van bij alle info cards. sterretje met gratis te kijken ofzo
